// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ChooseQuestions', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ChooseQuestions', async function() {
    await driver.get("http://localhost:8080/")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.css(".col-md-4:nth-child(2) > img")).click()
    await driver.findElement(By.css(".row:nth-child(2)")).click()
    await driver.findElement(By.css(".row:nth-child(1) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".row:nth-child(1) > .col-md-6:nth-child(2)")).sendKeys("Учитель математики")
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6:nth-child(2)")).sendKeys("тест 9 класс")
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Математика']")).click()
    }
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".col-md-6 > .btn")).click()
    await driver.findElement(By.css("tr:nth-child(2) .btn")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(2) .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("tr:nth-child(3) .btn")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(3) .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("tr:nth-child(4) .btn")).click()
  })
})
