// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('pulTest', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('pulTest', async function() {
    await driver.get("http://localhost:8080/")
    await driver.manage().window().setRect(1552, 840)
    await driver.findElement(By.linkText("Создать тест")).click()
    {
      const element = await driver.findElement(By.linkText("Создать тест"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".row:nth-child(1) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".row:nth-child(1) > .col-md-6:nth-child(2)")).sendKeys("тест пул")
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6:nth-child(2)")).sendKeys("тест")
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Математика']")).click()
    }
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6:nth-child(2)")).click()
    await driver.findElement(By.css(".col-md-6 > .btn")).click()
    await driver.findElement(By.css("tr:nth-child(5) .btn")).click()
    {
      const element = await driver.findElement(By.css("tr:nth-child(5) .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("tr:nth-child(4) .btn")).click()
    await driver.findElement(By.css("tr:nth-child(3) .btn-success")).click()
    await driver.findElement(By.css("tr:nth-child(2) input")).click()
    await driver.findElement(By.css("tr:nth-child(2) input")).sendKeys("1")
    await driver.findElement(By.css("tr:nth-child(3) input")).click()
    await driver.findElement(By.css("tr:nth-child(3) input")).sendKeys("1")
    await driver.findElement(By.css("table:nth-child(1) > tr:nth-child(4) > td:nth-child(5)")).click()
    await driver.findElement(By.css("tr:nth-child(4) input")).sendKeys("2")
    await driver.findElement(By.css(".col-md-8 > .btn")).click()
  })
})
